# TravisCI configuration for php-stubs/woocommerce-stubs

language: "php"
os:
  - "linux"
dist: "bionic"

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - "7.4"
  - "7.3"
  - "7.2"
  - "7.1"
  # giacocorsiglia/stubs-generator does not support PHP 7.0

before_install:
  - "phpenv config-rm xdebug.ini"
  - "composer self-update --1"
  - "composer validate --strict"

install:
  - "composer update --no-interaction --no-suggest"
  # Reinstall sub-packages into /packages/
  - "composer update --no-interaction --no-suggest"

before_script:
  - "cat ./source/woocommerce/woocommerce.php"

script:
  - "bash -x ./generate.sh"
  - "php -l woocommerce-stubs.php"
  - "php -l woocommerce-packages-stubs.php"
  - "git diff --exit-code"
  - |
    php -r 'require "vendor/php-stubs/wordpress-stubs/wordpress-stubs.php"; require "woocommerce-stubs.php"; require "woocommerce-packages-stubs.php";'
